# config.properties
browser=chrome
url=https://www.saucedemo.com/v1/index.html
Url2=https://seleniumpractise.blogspot.com/2021/08/webtable-in-html.html
cascadeUrl=http://www.postalpincode.in/Search-By-Location